feat: transferImage from dataURL
DreamOfIce/koishi-plugin-adapter-villa pull request #3
Opened 2023-08-06 19:03 UTC by dragon-fish

RT

2023-08-06 19:30 UTC, dragon-fish commented
this will fix #5

2023-08-07 14:17 UTC, DreamOfIce requested changes
请参照review进行修改

2023-08-07 14:17 UTC, DreamOfIce commented on src/utils/transferImage.ts
> +let routerInitialized = false;
这个不需要，revert下

2023-08-07 14:17 UTC, DreamOfIce commented on src/utils/transferImage.ts
> +  if (!routerInitialized) {
这个不需要，revert下

2023-08-07 14:17 UTC, DreamOfIce commented on src/utils/transferImage.ts
> +      `${this.config.path}/:hash(\\w+).:ext([a-zA-Z]+)`,
ext可能有数字和横杠的，原来那样就行

2023-08-07 14:17 UTC, DreamOfIce commented on src/utils/transferImage.ts
> +          ctx.res.setHeader("Content-Type", `image/${ext}`);
这里会自动设置的，而且mime和ext不一定相同

2023-08-07 14:17 UTC, DreamOfIce commented on src/utils/transferImage.ts
> +      return transferImage.call(
别这么搞，性能太差了

2023-08-08 16:36 UTC, closed without merging